### ISSUE TITLE
h5py and -disable-mpiio

### ISSUE THREAD

**Issue by sigbjobo** [Cascella-Group-UiO/HyMD#100]
The option for --disable-mpiio seems not to work. 

Managed to get it working installing parallel h5py by:
conda install -c conda-forge "h5py>=2.9=mpi*"
Which might be good to put in the guide!

Error with  --disable-mpiio
    with h5py.File(args.input, "r", driver=driver, comm=comm) as in_file:
  File "/home/sigbjobo/software/miniconda3/lib/python3.9/site-packages/h5py/_hl/files.py", line 441, in __init__
Traceback (most recent call last):
  File "/home/sigbjobo/Downloads/HyMD-2021/hymd/main.py", line 286, in <module>
    fapl = make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0, **kwds)
  File "/home/sigbjobo/software/miniconda3/lib/python3.9/site-packages/h5py/_hl/files.py", line 136, in make_fapl
    raise TypeError(msg)
TypeError: 'comm' is an invalid keyword argument for this function
    with h5py.File(args.input, "r", driver=driver, comm=comm) as in_file:
  File "/home/sigbjobo/software/miniconda3/lib/python3.9/site-packages/h5py/_hl/files.py", line 441, in __init__
    fapl = make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0, **kwds)
  File "/home/sigbjobo/software/miniconda3/lib/python3.9/site-packages/h5py/_hl/files.py", line 136, in make_fapl
    raise TypeError(msg)
TypeError: 'comm' is an invalid keyword argument for this function

**Comment by mortele** [comment]
Sorry for the issue necromancy, but this works now as far as I can tell.
