### ISSUE TITLE
Hamiltonian tests fail with sympy 1.10

### ISSUE THREAD

**Issue by mortele** [Cascella-Group-UiO/HyMD#164]
Works with `sympy 1.9`. [Changelog for 1.10](https://github-wiki-see.page/m/sympy/sympy/wiki/Release-Notes-for-1.10) which apparently breaks something in HyMD.

**Comment by mortele** [comment]
The code itself also fails 
```python
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/mortenledum/Documents/HyMD-docs-update/hymd/__main__.py", line 2, in <module>
    main()
  File "/Users/mortenledum/Documents/HyMD-docs-update/hymd/main.py", line 150, in main
    hamiltonian = DefaultNoChi(config)
  File "/Users/mortenledum/Documents/HyMD-docs-update/hymd/hamiltonian.py", line 192, in __init__
    self.setup()
  File "/Users/mortenledum/Documents/HyMD-docs-update/hymd/hamiltonian.py", line 200, in setup
    self.v_ext = [
  File "/Users/mortenledum/Documents/HyMD-docs-update/hymd/hamiltonian.py", line 201, in <listcomp>
    sympy.lambdify([self.phi], sympy.diff(w(self.phi), "phi%d" % (i)))
  File "/usr/local/lib/python3.9/site-packages/sympy/core/function.py", line 2499, in diff
    return f.diff(*symbols, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sympy/core/expr.py", line 3528, in diff
    return _derivative_dispatch(self, *symbols, **assumptions)
  File "/usr/local/lib/python3.9/site-packages/sympy/core/function.py", line 1923, in _derivative_dispatch
    return Derivative(expr, *variables, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sympy/core/function.py", line 1307, in __new__
    v = _sympify(v)
  File "/usr/local/lib/python3.9/site-packages/sympy/core/sympify.py", line 528, in _sympify
    return sympify(a, strict=True)
  File "/usr/local/lib/python3.9/site-packages/sympy/core/sympify.py", line 449, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: 'phi0'
```
