### ISSUE TITLE
numpy.distutils being dropped

### ISSUE THREAD

**Issue by hmcezar** [Cascella-Group-UiO/HyMD#195]
The support of distutils being dropped [soon](https://numpy.org/devdocs/reference/distutils_status_migration.html). CI failed in one of my  PR and that's probably the reason.

```bash
Run python3 -m pip install .
Processing /home/runner/work/HyMD/HyMD
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      <string>:2: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-4727vw_b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 337, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-4727vw_b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 319, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-4727vw_b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 474, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-4727vw_b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 334, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
        File "/tmp/pip-build-env-4727vw_b/overlay/lib/python3.8/site-packages/numpy/distutils/core.py", line 24, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File "/tmp/pip-build-env-4727vw_b/overlay/lib/python3.8/site-packages/numpy/distutils/command/config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "/tmp/pip-build-env-4727vw_b/overlay/lib/python3.8/site-packages/numpy/distutils/mingw32ccompiler.py", line 28, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Error: Process completed with exit code 1.
```

We should move our setup to something else.

**Comment by hmcezar** [comment]
Since we can just pin `setuptools` for now, we don't need to immediately change our build system. However, we should think for an actual solution mid to long-term.

I think our alternatives are:
- Build using `meson`.
- Wait for `setuptools` to implement features from `numpy.distutils`. Specifically, we need support for Fortran compilation, which might not be implemented so soon, or at all.
- Work on moving the force kernels to C as already started in #188 and build using `setuptools`.

SciPy (and soon numpy) went the meson way (see [this post](https://labs.quansight.org/blog/2021/07/moving-scipy-to-meson)).
Personally, I like the idea of learning how to use meson, as it might be a useful skill, but we need to think about the pros/cons of each alternative.
